#!/bin/python

import os
import argparse

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("filename", help="Filename to create")
    parser.add_argument("path", help="Path to create the file")
    args = parser.parse_args()
    
    filename = args.filename
    path = args.path

    if not os.path.isfile(path):

        file = open(path + '/' + filename + '.h', 'w')

        file.write(
            "// Auto generated by Nixsm\n"
            "#ifndef " + filename.upper() + "_VISIBILITY_H\n" +
            "#define " + filename.upper() + "_VISIBILITY_H\n\n" +
            "#if defined _WIN32 || defined __CYGWIN__\n" +
            "#   define " + filename.upper() + "_SHARED_HERE __declspec(dllexport)\n" +
            "#   define " + filename.upper() + "_SHARED_THERE  __declspec(dllimport)\n" +
            "#if __GNUC__ >= 4\n" +
            "#   define " + filename.upper() + "_SHARED_CLASS_HERE __declspec(dllexport)\n" +
            "#   define " + filename.upper() + "_SHARED_CLASS_THERE __declspec(dllimport)\n" +
            "#else\n" +
            "#   define " + filename.upper() + "_SHARED_CLASS_HERE\n" +
            "#   define " + filename.upper() + "_SHARED_CLASS_THERE\n" +
            "#endif\n" +
            "#   define " + filename.upper() + "_LOCAL_HERE\n" +
            "#   define " + filename.upper() + "_LOCAL_THERE\n" +
            "#else\n" +
            "#   if __GNUC__ >= 4\n" +
            "#       define " + filename.upper() + "_SHARED_CLASS_HERE __attribute__ ((visibility (\"default\")))\n" +
            "#       define " + filename.upper() + "_SHARED_CLASS_THERE __attribute__ ((visibility (\"default\")))\n" + 
            "#       define " + filename.upper() + "_SHARED_HERE __attribute__ ((visibility (\"default\")))\n" +
            "#       define " + filename.upper() + "_SHARED_THERE __attribute__ ((visibility (\"default\")))\n" +
            "#       define " + filename.upper() + "_LOCAL_HERE  __attribute__ ((visibility (\"hidden\")))\n" +
            "#       define " + filename.upper() + "_LOCAL_THERE  __attribute__ ((visibility (\"hidden\")))\n" +
            "#   else\n" +
            "#       define " + filename.upper() + "_SHARED_HERE\n" +
            "#       define " + filename.upper() + "_SHARED_THERE\n" +
            "#       define " + filename.upper() + "_LOCAL_HERE\n" +
            "#       define " + filename.upper() + "_LOCAL_THERE\n" +
            "#   endif\n" +
            "#endif\n" +
            "\n" +
            "#if defined(" + filename.upper() + "_EXPORTS) || defined(" + filename.upper() + "_EXPORTS)\n" + 
            "#   define " + filename.upper() + "_SHARED " + filename.upper() + "_SHARED_HERE\n" + 
            "#else\n" +
            "#   define " + filename.upper() + "_SHARED " + filename.upper() + "_SHARED_THERE\n" + 
            "#endif\n" + 
            "\n" + 
            "#endif//" + filename.upper() + "_VISIBILITY_H\n" + 
            "\n" +
            "\n"
        )

        print("Done")
    else:
        print('File exists')
